#!/bin/bash
#
# [Quick Box]
#
# GitHub:   https://github.com/JMSDOnline/QuickBox
# Author:   Swizards.net
# URL:      https://swizards.net
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
# 
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software 
#   including (via compiler) GPL-licensed code must also be made available 
#   under the GPL along with build & install instructions.
#
REALM=rutorrent
HTPASSWD=/etc/htpasswd
echo -n "Username: "; read user
        username=$(echo "$user"|sed 's/.*/\L&/')
        if [[ ! $(grep "^${username}" ${HTPASSWD}) ]]; then 
		echo "Username ${username} wasnt found in ${HTPASSWD} .. please try again"
		exit
	fi
        echo -n "Password: (hit enter to generate a password) "; read password
        if [[ ! -z "${password}" ]]; then
                echo "setting password to ${password}"
                passwd=${password}
                echo "${username}:${passwd}" | chpasswd >/dev/null 2>&1
                sed -i "/^${username}/d" ${HTPASSWD}
                (echo -n "${username}:${REALM}:" && echo -n "${username}:${REALM}:${passwd}" | md5sum | awk '{print $1}' ) >> "${HTPASSWD}"
        else
                echo "setting password to ${genpass}"
                sed -i "/^${username}/d" ${HTPASSWD}
                passwd=${genpass}
                echo "${username}:${passwd}" | chpasswd >/dev/null 2>&1
                (echo -n "${username}:${REALM}:" && echo -n "${username}:${REALM}:${passwd}" | md5sum | awk '{print $1}' ) >> "${HTPASSWD}"
        fi
	echo "$username : $passwd" >>/root/${username}.info
