#!/bin/bash
#
# [Quick Box]
#
# GitHub:   https://github.com/JMSDOnline/QuickBox
# Author:   Jason Matthews
# URL:      https://jmsolodesigns.com
#
OUTTO=/dev/null
export USER=`id -un`
killall -u $USER irssi >>"${OUTTO}" 2>&1
killall -u $USER rtorrent >>"${OUTTO}" 2>&1
killall -U $USER main >>"${OUTTO}" 2>&1
rm -rf ~/.sessions/rtorrent.lock
