#!/bin/bash
#
# [Quick Box :: Install create plugin]
#
# GitHub:   https://github.com/JMSDOnline/quick-box
# Author:   Jason Matthews
# URL:      https://jmsolodesigns.com/code-projects/quick-box/seedbox-installer
#

function _installplugin-create() {
  rutorrent="/srv/rutorrent/";
  PLUGINVAULT="/etc/quickbox/rutorrent/plugins/"; cd "${rutorrent}plugins"
  PLUGIN="create"
    for i in $PLUGIN; do
      cp -R "${PLUGINVAULT}$i" .
    done
    chown -R www-data: ${rutorrent}plugins/$PLUGIN
    cd
}

_installplugin-create