#!/bin/bash
#
# [Quick Box :: Install autodl plugin]
#
# GitHub:   https://github.com/JMSDOnline/QuickBox
# Author:   Jason Matthews
# URL:      https://jmsolodesigns.com/code-projects/quick-box/seedbox-installer
#

function _installplugin-autodl() {
  username=$(whoami);
  rutorrent="/srv/rutorrent/";
  PLUGINVAULT="/etc/quickbox/plugins/"; cd "${rutorrent}plugins"
  PLUGIN="autodl-irssi"
    for i in $PLUGIN; do
      cp -R "${PLUGINVAULT}$i" .
    done
  chown -R www-data: ${rutorrent}plugins/$PLUGIN
}

_installplugin-autodl