#!/bin/bash
#
# [Quick Box :: Remove rss plugin]
#
# GitHub:   https://github.com/JMSDOnline/quick-box
# Author:   Jason Matthews
# URL:      https://jmsolodesigns.com/code-projects/quick-box/seedbox-installer
#

function _removeplugin-rss() {
  rutorrent="/srv/rutorrent/";
  PLUGIN="rss"
    for i in $PLUGIN; do
      rm -rf "${rutorrent}plugins/$i"
    done
}

_removeplugin-rss