#!/bin/bash
#
# [Quick Box :: Remove scheduler plugin]
#
# GitHub:   https://github.com/JMSDOnline/QuickBox
# Author:   Jason Matthews
# URL:      https://jmsolodesigns.com/code-projects/quick-box/seedbox-installer
#

function _removeplugin-scheduler() {
  rutorrent="/srv/rutorrent/";
  PLUGIN="scheduler"
    for i in $PLUGIN; do
      rm -rf "${rutorrent}plugins/$i"
    done
}

_removeplugin-scheduler