#!/bin/bash
#
# [Quick Box :: Remove show_peers_like_wtorrent plugin]
#
# GitHub:   https://github.com/JMSDOnline/QuickBox
# Author:   Jason Matthews
# URL:      https://jmsolodesigns.com/code-projects/quick-box/seedbox-installer
#

function _removeplugin-show_peers_like_wtorrent() {
  rutorrent="/srv/rutorrent/";
  PLUGIN="show_peers_like_wtorrent"
    for i in $PLUGIN; do
      rm -rf "${rutorrent}plugins/$i"
    done
}

_removeplugin-show_peers_like_wtorrent